project:
  type: website

website: 
  title: "vbaliga.github.io"
  site-url: https://vbaliga.github.io
  repo-url: https://github.com/vbaliga/vbaliga.github.io
  twitter-card: 
    site: "@labrichthys"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
    
editor: visual

