project:
  type: website
  output-dir: docs

editor: 
  mode: source
  markdown:
    wrap: 80
    canonical: true
    
execute:
  freeze: auto

description-meta: "Personal site for Yujun Lian"

website: 
  title: "lianyujun.github.io"
  site-url: https://lianyujun.github.io
  repo-url: https://github.com/lianyujun/lianyujun.github.io
  image: "/images/lianyujun_2025.jpg"
  open-graph:
    image: "/images/lianyujun_2025_full.jpg"
    locale: en_US
  favicon: "/images/site-logo.png"
  navbar:
    pinned: true
    background: "#EE6A24"
    right:
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Codes"
        href: codes.qmd
      - text: "Blogs"
        href: blog.qmd
  search:
    location: navbar
    type: overlay
  page-footer:
    left: |
      [lianxh.cn](https://www.lianxh.cn)<br>
    right: |
      Made with [Quarto](https://quarto.org/)<br>

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
    code-overflow: wrap
    include-in-header: 
      - file: head_tag.html
      - text: |
          <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
          <style>
            body { font-family: 'Poppins', sans-serif; }
          </style>
    include-before-body: 
      - file: ga4_tag.html
